### ISSUE TITLE
Getting a rename error when trying to use parsnip for classification

### ISSUE THREAD

**Issue by clibassi** [NickCH-K/MLRtime#2]
Hi Nick - 

Just having a weird issue that might just be me misspecifying something in the syntax, but wanted to see if you know what might be going on. I got it to reproduce with the auto dataset and here's the code that produces it for me: 

```
clear all
set more off 
sysuse auto, clear 
gen test = runiformint(0, 1)
parsnip i.foreign index price mpg,  ///
	hold(test) mode(classification) model(rand_forest) replace clearR pred(RF_prediction)
```

Here's what I get out as an error: 

![image](https://user-images.githubusercontent.com/10570262/144724886-eb4532f2-b82c-46d8-a6f7-05dd83f6f777.png)

And here's what trace shows: 

![image](https://user-images.githubusercontent.com/10570262/144724916-909be70f-6212-4c57-a62d-69743f7d5133.png)

**Comment by NickCH-K** [comment]
Parsnip has some issues with left hand side factors, and the docs recommend converting it to a string (and not using i.). I'll check if that fixes it once I'm back to the computer.

**Comment by clibassi** [comment]
Oh I just checked it and that works - thank you!
